import {useEffect,useState} from "react";
import {Package,ScanLine,ShieldAlert,TrendingUp,ArrowUpRight,Activity} from "lucide-react";
import {AreaChart,Area,ResponsiveContainer,XAxis,YAxis,Tooltip,CartesianGrid} from "recharts";
import api from "../api";
export default function Dashboard(){const [s,setS]=useState(null),[t,setT]=useState([]);const load=()=>Promise.all([api.get("/api/dashboard/summary"),api.get("/api/dashboard/trends")]).then(([a,b])=>{setS(a.data);setT(b.data)});useEffect(()=>{load()},[]);
 const cards=[[Package,"Active batches",s?.batches||0,"Across inventory"],[ScanLine,"AI assessments",s?.assessments||0,"Freshness analyses"],[ShieldAlert,"Open alerts",s?.unread_alerts||0,"Need attention"],[TrendingUp,"Health score",s?.average_score||0,"Platform average"]];
 return <><div className="hero"><div><span className="eyebrow">LIVE MONITORING</span><h1>Know what’s fresh.<br/><em>Act before it spoils.</em></h1><p>Monitor inventory, predict freshness and take action before quality declines.</p></div><div className="hero-score"><small>AVERAGE FRESHNESS</small><strong>{s?.average_score||0}</strong><span>/ 100 quality score</span></div></div>
 <div className="stats">{cards.map(([I,l,v,sub])=><div className="stat" key={l}><span className="stat-icon"><I/></span><div><small>{l}</small><strong>{v}</strong><span>{sub}</span></div></div>)}</div>
 <div className="grid2"><div className="panel"><div className="panel-head"><div><h3>Freshness trend</h3><span>Recent assessment scores</span></div><Activity/></div>{t.length?<ResponsiveContainer width="100%" height={270}><AreaChart data={t}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#b9ed58" stopOpacity=".65"/><stop offset="100%" stopColor="#b9ed58" stopOpacity=".05"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#edf1eb"/><XAxis dataKey="date"/><YAxis domain={[0,100]}/><Tooltip/><Area type="monotone" dataKey="score" stroke="#4b7f38" fill="url(#g)" strokeWidth={3}/></AreaChart></ResponsiveContainer>:<Empty title="No assessments yet" text="Run a freshness analysis to build your trend."/>}</div>
 <div className="panel"><div className="panel-head"><div><h3>Quality distribution</h3><span>Current classifications</span></div></div><div className="quality-list">{Object.keys(s?.categories||{}).length?Object.entries(s.categories).map(([k,v])=><div className="quality-row" key={k}><span>{k}</span><b>{v}</b></div>):<Empty title="No classifications yet" text="Your assessment results will appear here."/>}</div></div></div></>}
function Empty({title,text}){return <div className="empty"><div>◌</div><b>{title}</b><span>{text}</span></div>}
