import {useEffect,useState} from "react";
import {ScanLine,Upload,CheckCircle,Clock3,AlertTriangle,RefreshCw} from "lucide-react";
import api from "../api";
export default function Freshness(){const [batches,setBatches]=useState([]),[batch,setBatch]=useState(""),[file,setFile]=useState(null),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[assess,setAssess]=useState([]),[msg,setMsg]=useState("");const load=async()=>{const [b,a]=await Promise.all([api.get("/api/inventory/batches"),api.get("/api/freshness/assessments")]);setBatches(b.data);setAssess(a.data)};useEffect(()=>{load()},[]);
 const analyze=async e=>{e.preventDefault();if(!batch)return setMsg("Select a food batch.");setBusy(true);setMsg("");try{const fd=new FormData();fd.append("batch_id",batch);if(file)fd.append("image",file);const r=await api.post("/api/freshness/analyze",fd,{headers:{"Content-Type":"multipart/form-data"}});setResult(r.data);load()}catch(x){setMsg(x.response?.data?.detail||"Analysis failed")}finally{setBusy(false)}};
 return <><div className="page-head"><div><span className="eyebrow">AI FRESHNESS ENGINE</span><h1>Freshness analysis</h1><p>Combine visual input, storage conditions and shelf-life data into one quality score.</p></div><button className="icon-btn" onClick={load}><RefreshCw/></button></div>
 <div className="analysis-grid"><div className="panel analysis-form"><div className="panel-head"><div><h3>Run new analysis</h3><span>Select a batch and optionally upload an image.</span></div><ScanLine/></div><form onSubmit={analyze}><label>Food batch<select required value={batch} onChange={e=>setBatch(e.target.value)}><option value="">Select batch</option>{batches.map(b=><option key={b.id} value={b.id}>{b.batch_code} — {b.food_name}</option>)}</select></label><label>Food image <span className="optional">optional</span><div className="drop"><Upload/><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><b>{file?file.name:"Choose an image"}</b><span>JPG, PNG or WebP</span></div></label>{msg&&<div className="error">{msg}</div>}<button className="primary wide" disabled={busy}>{busy?"Analyzing…":"Run freshness analysis"}<ScanLine/></button></form></div>
 <div className="panel result-panel">{result?<Result r={result}/>:<div className="empty big"><ScanLine/><b>Your result will appear here</b><span>Select a batch and run the analysis.</span></div>}</div></div>
 <div className="panel"><div className="panel-head"><div><h3>Assessment history</h3><span>Latest freshness assessments</span></div></div>{assess.length?<div className="assessment-list">{assess.map(a=><div className="assessment" key={a.id}><div className={`score-dot ${a.score>=65?"green":a.score>=50?"amber":"red"}`}>{Math.round(a.score)}</div><div className="assessment-main"><b>{a.category}</b><span>{a.recommendation}</span></div><div className="assessment-meta"><span><Clock3/> {a.remaining_days} days</span><small>{new Date(a.created_at).toLocaleString()}</small></div></div>)}</div>:<div className="empty"><b>No assessments yet</b><span>Run your first analysis.</span></div>}</div></>}
function Result({r}){return <div className="result"><div className="result-score"><div><small>QUALITY SCORE</small><strong>{Math.round(r.score)}</strong><span>/ 100</span></div><div className={`result-status ${r.score>=65?"fresh":r.score>=50?"acceptable":"risk"}`}>{r.category}</div></div><div className="metrics"><Metric n="Visual" v={r.visual_score}/><Metric n="Storage" v={r.storage_score}/><Metric n="Shelf life" v={r.shelf_score}/><Metric n="Age" v={r.age_score}/></div><div className="result-bottom"><div><b>Remaining shelf life</b><strong>{r.remaining_days} days</strong></div><div><b>Spoilage probability</b><strong>{Math.round(r.spoilage_probability*100)}%</strong></div><div><b>Confidence</b><strong>{Math.round(r.confidence*100)}%</strong></div></div><div className="recommend"><AlertTriangle/><div><b>Recommendation</b><span>{r.recommendation}</span><small>{JSON.parse(r.indicators||"[]").join(" • ")}</small></div></div></div>}
function Metric({n,v}){return <div><span>{n}</span><b>{Math.round(v)}</b><div className="meter"><i style={{width:`${v}%`}}/></div></div>}
